version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Конфиг Nginx
      - ./public_html:/var/www/html  # Сайт и API файлы из public_html
    depends_on:
      - php
      - frontend

  php:
    #image: php:8.2-fpm
    build: ./docker/php
    container_name: php
    restart: always
    volumes:
      - ./public_html/backend:/var/www/html/backend  # Сайт и API файлы из public_html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini  # Конфиг PHP

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
    volumes:
      - ./data/mariadb:/var/lib/mysql  # Указываем физическую папку на хосте для данных
    ports:
      - "3306:3306"

  frontend:
    build: ./public_html/frontend
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./public_html/frontend:/app  # Связываем папку frontend с контейнером для Nuxt
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    #command: ["npm", "run", "start"]  # Запуск Nuxt в режиме SSR ["npm", "run", "start"] "sh", "-c", "npm run build && npm run start"

volumes:
  mariadb_data: {} # Тома не требуется, так как мы используем bind mount для данных MariaDB docker run -it proj1_frontend:latest sh